### ISSUE TITLE
Identify a good vector base layer source (OpenStreetMap or similar)

### ISSUE THREAD

**Issue by BobTorgerson** [ua-snap/snap-arctic-portal#1]
Identify a good vector base layer source for GeoNode in an arctic projection. Many are available, need to choose one that would be ideal for re-projection and use.

**Comment by brucecrevensten** [comment]
I'll clear this back for more scrutiny later.

My initial thought was that we could compose our own vector map base layer from easily-found vector shapefiles used by GIS folks in AK.  I talked with Keith about this.  I don't think we can really get what we want, here, but will need to talk back more with some GIS folks about this.
