### ISSUE TITLE
Implement “automated deployment” for MapLoom

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/snap-arctic-portal#10]

**Comment by brucecrevensten** [comment]
Just need to confirmed/re-check and update docs as appropriate.

**Comment by BobTorgerson** [comment]
Make the development script setup PostGIS for storing the geospatial data rather than in SQLite. This will allow for the development instances be able to pull a dump from the production instance to host the data locally.

**Comment by cstephen** [comment]
@BobTorgerson was your comment meant for issue #23? Maybe this happened during this meeting's waffle.io misfire.

This issue, as I understand it, is to set up a simple `update_maploom.sh` sort of script that compiles and copies the new MapLoom file into place. Looks like this is assigned to me now, so I'm on it.

**Comment by cstephen** [comment]
Bob's comment was written before issue #23 was created, so setting up the development environment with PostGIS rather than SQLite is no longer part of this issue.

**Comment by BobTorgerson** [comment]
This issue is for the deployment of the initial install of GeoNode + MapLoom + SNAPMAPAPP, specifically to our Vagrant instances for development. This is in a good state as of the most recent branch push in: https://github.com/ua-snap/vagrant-geonode/tree/snapmapapp
