### ISSUE TITLE
Ensure all maps except Fire map are marked Beta initially on AWS

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/snap-arctic-portal#123]
To clarify: those maps should be marked as "not published" in GeoNode until Tom has reviewed at least the IAM map.

**Comment by brucecrevensten** [comment]
I tried this on the AWS instance (setting `isPublished = False`) for the IAM map and it didn't have any effect on the catalog screen.  @cstephen can you check this?  Not sure what's up here.

**Comment by cstephen** [comment]
Looks like we just need to set the following in `/var/www/geonode/geonode/settings.py` on the AWS instance:

```
RESOURCE_PUBLISHING = True
```

@BobTorgerson, can I go ahead and make this change on our AWS instance, or is this the kind of thing that needs to be added to the provisioning process? Or both?

**Comment by cstephen** [comment]
We fixed this setting on the AWS GeoNode instance and the unpublished maps no longer appear on http://mapventure.org

**Comment by cstephen** [comment]
I've marked the "Integrated Arctic Management" map as "not published" now, too, so only the Fire map is public on http://mapventure.org
