### ISSUE TITLE
Explore these data resources

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/snap-arctic-portal#17]
The goal of this ticket is to enjoy a day of surfing through various climate-related data sites/apps/portals/tools.

Ideally, we'd find some treasure chests of data that we could use on our own project, along with some better sense of great/not-so-great approaches that other people have taken in this space.

**Comment by brucecrevensten** [comment]
Federal-level climate data / SNAP integration

Look for: "Climate Data Toolkit" in addition to these (may be implicit below, "Climate Explorer").

http://data.worldbank.org/climate-change

http://www.data.gov/climate/

http://www.esri.com/esri-news/releases/14-1qtr/esri-supports-white-house-climate-data-initiative

http://resilience.maps.arcgis.com/home/

http://toolkit.climate.gov/tools

http://downloads.esri.com/agol/org/resilience/gallery/climate/

**Comment by brucecrevensten** [comment]
To finish this, complete a writeup in a shared doc of findings!

**Comment by cstephen** [comment]
I've shared my findings document. Consider this closed!
