### ISSUE TITLE
Allow web connection to GeoServer on test instance

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/snap-arctic-portal#18]
Need to put some simple authentication in place for this.  On dev it runs on port 8080 which is fine for the test instance.

**Comment by cstephen** [comment]
You can access GeoServer as you normally would by going to `/geoserver` on the geonode-test.iarc.uaf.edu. Even when accessing GeoServer through port 8080 on a development instance, you still have to go to `/geoserver` to access Tomcat's GeoServer web app. In other words, the Apache proxy to port 8080 gives us full access to all of GeoServer without any collisions. Please clarify if there's more to this.

**Comment by brucecrevensten** [comment]
Nope, that makes sense!  I was used to just going to port 8080 locally so hadn't used the `/geoserver` route.
