### ISSUE TITLE
Make embedded map in GeoNode work with EPSG:3338 projection

### ISSUE THREAD

**Issue by cstephen** [ua-snap/snap-arctic-portal#19]
EPSG:3338 projections are working with the "full view" MapLoom interface, but the embedded map that shows up on GeoNode's layer preview page has not yet been modified to support EPSG:3338. GeoNode defaults to GeoExplorer for this embedded map, but it can be changed to Leaflet by adding the following line to our `local_settings.py` file:

```
LAYER_PREVIEW_LIBRARY = 'leaflet'
```

This loads the Leaflet Django app. Information on how to configure Leaflet through Django is here:

https://github.com/makinacorpus/django-leaflet

I experimented with this a little bit but haven't gotten Leaflet working with EPSG:3338 yet.

**Comment by brucecrevensten** [comment]
So after discussing this we think we can leave the map in default 3857 for the embedded/preview map, but we should have a base layer present.

**Comment by brucecrevensten** [comment]
Definitely not doing this; we may need to see why GeoNode doesn't display previews correctly but we're not using GeoNode as the primary display vehicle for our maps & layers.
