### ISSUE TITLE
Establish process for doing DB sync

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/snap-arctic-portal#23]
From test server back to dev computer, in particular, will help us share more data sets and so on.  How can this work?

**Comment by BobTorgerson** [comment]
I've modified the automated provisioning script to install PostGIS and use it as the main database for GeoNode. This allows us to have a more production-like environment and for my two new scripts: backup.sh and restore.sh to create a backup of GeoNode and GeoServer and restore them on a different development server. Unfortunately, these scripts will not work unless you're development environment is already using PostGIS as its main database. These scripts and changes are available in the branch postgis: https://github.com/ua-snap/vagrant-geonode/tree/postgis
