### ISSUE TITLE
Create script to automate production code update

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/snap-arctic-portal#31]
This would need to `git pull` and `grunt` and perhaps a few files need to get copied around.

**Comment by BobTorgerson** [comment]
I've got a start on this I believe with the update_geonode.sh script in the branch: snapmapapp. https://github.com/ua-snap/vagrant-geonode/blob/snapmapapp/geonode/update_geonode.sh

This should git pull the latest changes to our MapLoom repository, and run the commands to rebuild if the repository wasn't already up to date and then moves on to git pull the latest changes for the snapmapapp if any are available.

**Comment by brucecrevensten** [comment]
Need to test this + finalize changes as needed in next sprint.

**Comment by brucecrevensten** [comment]
This is on hold until we finalize our production stance re: MapVenture + GeoNode

**Comment by BobTorgerson** [comment]
A new script has been created on geonode.iarc.uaf.edu for MapVenture. The script can be run like:

`ssh -p 2222 <username>@geonode.iarc.uaf.edu /usr/local/bin/update_mapventure.sh`

Here is the full script below:

```
#! /bin/bash

# Move into MapVenture directory
cd /var/www/mapventure/

# Pull any new changes into repository
sudo -u www-data git pull

# Bower install any new bower dependencies
sudo -u www-data bower install

# Grunt build
sudo -u www-data grunt build --force

# Remove the previous HTML directory
sudo -u www-data rm -rf /var/www/html

# Move the built distribution to the html directory
sudo -u www-data mv dist /var/www/html
```
