### ISSUE TITLE
Create a sensible front page

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/snap-arctic-portal#32]
Goal here is time-boxed (1 day), just to get something that looks like a real home page for the site and isn't GeoNode branded anymore.  Nongoal: final design + content of home page + site.

**Comment by BobTorgerson** [comment]
The home page for the GeoNode site is found in: ~/geonode/geonode/templates
All of the pages in GeoNode are derived from the base.html document which contains definitions for the <head>, header and footer section for the site. The home page itself is contained within index.html within this directory as you might expect. 

The base CSS file is found in: ~/geonode/geonode/static/geonode/css/base.css 
Modifying “jumbotron” tag modifies the big banner portion of the home page.

**Comment by brucecrevensten** [comment]
We're not doing this for our GeoNode instance and we're not taking the "home page + catalog of maps" approach for MV work, so, closing!
