### ISSUE TITLE
Analysis: NCEP historical/projected temperature data

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/snap-arctic-portal#43]
Meet with J. Walsh, identify data source, determine work needed to get this rendered in GeoNode.

**Comment by brucecrevensten** [comment]
Initially let's limit the time allocated for this ticket to be small -- not a complete analysis, just enough to get the general sense of what may be involved.

**Comment by BobTorgerson** [comment]
For the NCEP historical data, I've written the beginnings of a script for automatically pulling down particular NetCDF datasets that are converted to GeoTIFF files appropriate for loading into GeoNode. Currently, I have the Sea Surface Temperature and Air Temperature both being downloaded and converted. 

For the projected data, I've gotten a GRIB2 file downloaded and converted into a GeoTIFF file using GDAL, but I'm not getting anything in GeoNode display. I can again see the data in a small thumbnail version of the uploaded data, but it is not displaying on the maps themselves. Here is an example of the data being used: ftp://ftp.cpc.ncep.noaa.gov/NMME/realtime_anom/NASA/2015090800/
