### ISSUE TITLE
Analysis: how to automate NCEP data ingest

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/snap-arctic-portal#53]

**Comment by BobTorgerson** [comment]
Pushed a new branch to vagrant-geonode called NCEP_data: https://github.com/ua-snap/vagrant-geonode/tree/NCEP_data

This has a new script called ncep_convert.sh which goes through the effort of downloading  the most recent daily, weekly, monthly, and yearly NetCDF files and converting them into a EPSG:4326 projected GeoTIFF, one for each of the NC files. These files are able to be viewed in QGIS, but I am still having difficulty getting them to appear in GeoNode. More exploration regarding GDAL's ability to change where the data begins and ends (not at the prime meridian for example) is likely needed for GeoNode to properly display the GeoTIFF.

**Comment by BobTorgerson** [comment]
We were correct about the prime meridian centering being the issue. Found information about how to do a gdalwarp that converts the beginning and the end of the data and GeoNode much prefers when the data starts at -180 and goes to 180. If it wraps around 0 to 360, it appears to have all kinds of issues displaying the data.
