### ISSUE TITLE
Create SNAP Arctic Portal Django App to modify layout/content for static content

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/snap-arctic-portal#9]

**Comment by brucecrevensten** [comment]
We have a need to fiddle with the `local_settings.py` file in order to get the different base layer projections; is it possible that with [the approach we found outlined here](https://github.com/GeoNode/geonode-project) that this will allow us to manage that file properly?

**Comment by cstephen** [comment]
(Adapted from what I said in Slack.)

I made a few small changes to the `snapmapapp` branch of the snap-arctic-portal repo. Then I cloned and installed the repo like this:

```
cd ~
workon geonode
git clone git@github.com:ua-snap/snap-arctic-portal.git
git checkout snapmapapp
pip install -e snap-arctic-portal
```

Then edited `geonode/geonode/settings.py` and added `snapmapapp` like this:

```
INSTALLED_APPS = (
  ...
  'snapmapapp',
) + GEONODE_APPS
```

Then added our app's custom URL patterns _before_ GeoNode's pattern for the particular URL. So:

Edited `geonode/geonode/urls.py`, put this before the existing urlpatterns declaration:

```
from snapmapapp.urls import urlpatterns as snapmapapp_urls
urlpatterns = snapmapapp_urls
```

And changed the original `urlpatterns` declaration to append instead:

```
urlpatterns += patterns('',
...
```

Doing this, I was able to override the front page of GeoNode with a custom template.

**Comment by cstephen** [comment]
The `snapmapapp` branch of the snap-arctic-portal repo is working, as is the `snapmapapp` branch of the vagrant-geonode repo. So, once Bob is comfortable merging the branch in the snap-arctic-portal repo, then rewiring the branch in the vagrant-genode repo to checkout `master` instead of `snapmapapp`, I think we can close this issue. Reassigning to Bob.
